-- Enable Row Level Security
alter default privileges revoke execute on functions from public;

-- 1. PROFILES TABLE (Hero/Bio)
create table profiles (
  id uuid references auth.users not null primary key,
  full_name text,
  headline text,
  bio text,
  avatar_url text,
  hero_image_url text,
  updated_at timestamp with time zone
);

alter table profiles enable row level security;
create policy "Public profiles are viewable by everyone." on profiles for select using ( true );
create policy "Users can insert their own profile." on profiles for insert with check ( auth.uid() = id );
create policy "Users can update own profile." on profiles for update using ( auth.uid() = id );

-- 2. SKILLS TABLE
create table skills (
  id bigint generated by default as identity primary key,
  name text not null,
  type text not null, -- 'core' or 'tech_stack'
  icon_name text, -- For lucide (e.g., 'Server') or simple-icon slug
  image_url text, -- For custom SVG/PNG
  brand_color text,
  position integer,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

alter table skills enable row level security;
create policy "Skills are viewable by everyone." on skills for select using ( true );
create policy "Admins can insert skills." on skills for insert with check ( auth.role() = 'authenticated' );
create policy "Admins can update skills." on skills for update using ( auth.role() = 'authenticated' );
create policy "Admins can delete skills." on skills for delete using ( auth.role() = 'authenticated' );

-- 3. PROJECTS TABLE
create table projects (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  image_url text,
  year text,
  tools text[], -- Array of strings
  live_link text,
  github_link text,
  is_featured boolean default false,
  position integer,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

alter table projects enable row level security;
create policy "Projects are viewable by everyone." on projects for select using ( true );
create policy "Admins can insert projects." on projects for insert with check ( auth.role() = 'authenticated' );
create policy "Admins can update projects." on projects for update using ( auth.role() = 'authenticated' );
create policy "Admins can delete projects." on projects for delete using ( auth.role() = 'authenticated' );

-- 4. CERTIFICATIONS TABLE
create table certifications (
  id bigint generated by default as identity primary key,
  title text,
  image_url text not null,
  issuer text,
  issue_date date,
  credential_url text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

alter table certifications enable row level security;
create policy "Certifications are viewable by everyone." on certifications for select using ( true );
create policy "Admins can insert certifications." on certifications for insert with check ( auth.role() = 'authenticated' );
create policy "Admins can update certifications." on certifications for update using ( auth.role() = 'authenticated' );
create policy "Admins can delete certifications." on certifications for delete using ( auth.role() = 'authenticated' );

-- 5. PROFILE TABLE (singleton for hero/about)
create table profile (
  id bigint generated by default as identity primary key,
  display_name text,
  headline text,
  about_text text,
  avatar_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

alter table profile enable row level security;
create policy "Profile is viewable by everyone." on profile for select using ( true );
create policy "Admins can insert profile." on profile for insert with check ( auth.role() = 'authenticated' );
create policy "Admins can update profile." on profile for update using ( auth.role() = 'authenticated' );
